Update Readme.md
htmlacademy-htmlcss/992253-nerds-31 pull request #1
Opened 2021-06-21 13:57 UTC by Temirkhan9496

Добавил Наставника

2021-06-26 10:34 UTC, Viktor-Rybakov commented on index.html
> +    </a>
Отсутствует открывающий тег

2021-06-26 10:51 UTC, Viktor-Rybakov requested changes
Для первого раза очень хорошо!
Нужно сверстать слайдер, поправить ошибки
Посмотри, что выдает валидатор:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fhtmlacademy-htmlcss.github.io%2F992253-nerds-31%2F1%2F

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <h1>Долго, дорого, скрупулезно.</h1>
Этот заголовок не описывает сайт целиком. Он относится к слайдеру, на котором представлены различные акции, например. На ммакете в фигме можо включить и выключить слайды

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <h1>Долго, дорого, скрупулезно.</h1>
Здесь нужно разметить все слайды

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +          <li>
Элементы списка должны быть обернуты в тег списка ul или ol

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <section>
Это содержимое одного слайда (плюс заголовок "Долго, дорого, скрупулезно.")

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +            <img src="illustration-1.png" width="300" height="146" alt="картинка">
alt не информативный, если картинка не загрузится, то из этого описания будет понятно, что изображено?

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +        <h1>Мы — маленькая, но гордая дизайн-студия из Краснодара.</h1>
На сайте принято делать один заголовок уровня H1

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +         <br><p>Уровень самоотдачи 146%</p>
Здесь точно нужен перенос строки?

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +          <h1>Скрытые картинки</h1>
Неверный уровень заголовка

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +         <img src="nerds-illustration.png" width="360" height="208" alt="HTML Academy">
По ТЗ эти картинки должны быть ссылками (в ТЗ указана ссылка на страничу академии, посмотри)

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +         <img src="nerds-illustration.png" width="360" height="208" alt="HTML Academy">
И это однотипные элементы, которые можно представить списком

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +          <h1>NЁRDS DESIGN STUDIO</h1>
Неверный уровень заголовка

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <input id="text" type="text" name="name" placeholder="В свободной форме"><br>
Инпут с таким атрибутом name уже существует

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <a href="blank.html">Отправить</a>
Ссылка отправляет форму? Нужна кнопка

2021-06-26 10:51 UTC, Viktor-Rybakov commented on index.html
> +      <input id="text" type="text" name="name" placeholder="В свободной форме"><br>
Дублируется Id

2021-06-29 18:01 UTC, Viktor-Rybakov commented on index.html
> +          <ul>
В  список можно вкладывать только элементы li

2021-06-29 18:02 UTC, Viktor-Rybakov commented on index.html
> +         <img src="https://via.placeholder.com" width="360" height="208" alt="HTML Academy">
Картинки должны быть ссылками
https://up.htmlacademy.ru/htmlcss/31/project/nerds#nerds-3-6

2021-06-29 18:03 UTC, Viktor-Rybakov commented on index.html
> +      <input id="text" type="text" name="text" placeholder="В свободной форме"><br>
У этого инпута совпадает id и name с инпутом на строке 118

2021-07-07 07:23 UTC, Viktor-Rybakov requested changes
Отличная работа!!! Нужно поправить небольшие замечания, и обратить внимание на единообразие написания кода - теги в некоторых местах пишутся то маленькими буквами, то большими, то с большой буквы.
https://up.htmlacademy.ru/htmlcss/31/criteries#b15

2021-07-07 07:23 UTC, Viktor-Rybakov commented on index.html
> +          <img src="https://echo.htmlacademy.ru/" width="90" height="80" alt="Нёрдс">
Как дойдешь до графики, нужно будет вставить ссылку на логотип. А пока нет картинок, то можно использовать специальный сервис, который заменяет картинки: placeholder.com
Это не ошибка, просто совет.

2021-07-07 07:23 UTC, Viktor-Rybakov commented on index.html
> +        <LI>
Есть критерий - код должен быть написан единообразно  в одном стиле, если теги везде написаны прописными буквами, то и здесь нужно сделать так же

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +              <label for="filter-sliderr">Слайдер</label>
Опечатка в атрибуте for

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +              <label for="filter-Advantages">Блок преимуществ</label>
Атрибут for не соответствует атрибуту id элемента, на который он ссылается

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +    <section>
Эту часть фильтра тоже можно поместить в форму. Тогда это будет одна секция с одним общим заголовком, например "Фильтр шаблонов", форма будет разделена на логические блоки с помощью fieldset с заголовками legend

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +          <a>По типу</a>
Здесь тоже можно поставить атрибут с заглушкой.

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +      <h3>Сортировать:</h3>
В секции достаточно одного заголовка, это можно сделать обычным параграфом.

2021-07-07 07:23 UTC, Viktor-Rybakov commented on catalog.html
> +            <img src="#" width="210" height="200" alt="">
Нужно добавить описание картинки

2021-07-07 07:24 UTC, merged

2021-07-07 14:09 UTC, Temirkhan9496 commented
Сделал!